# Health Assistant App
# Copyright ACME Corporation
# SPDX-License-Identifier: Apache-2.0

# ? See https://pre-commit.com for more information
# ? See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude_types: [json]
        exclude: '(.*\.xcstrings|\.xcassets|\.svg)'
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-json
        types: [file]
        files: \.(json|xcstrings)$
        exclude: '(.*\.xcassets/.*\.json$)'
      - id: pretty-format-json
        args: ["--autofix", "--indent=4", "--top-keys=version,sourceLanguage"]
        types: [file]
        files: \.(json|xcstrings)$
        exclude: '(\.vscode/settings\.json|\.jtd\.json$|.*\.xcassets/.*|.*\.colorset/.*|\.animation\.lottie\.json$)'

  - repo: local
    hooks:
      - id: swiftlint
        name: SwiftLint
        description: "Check Swift files for issues with SwiftLint"
        entry: "swiftlint --quiet"
        language: system
        types: [swift]
        args: ["--use-alternative-excluding"]

      - id: swiftformat
        name: SwiftFormat
        description: "Check swift files for formatting issues with SwiftFormat"
        entry: swiftformat
        language: system
        types: [swift]
