# Health Assistant App
# Copyright ACME Corporation
# SPDX-License-Identifier: Apache-2.0

name: Linters - SwiftLint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.swift"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swiftlint:
    name: swiftlint
    runs-on: [ubuntu-24.04]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up mise
        uses: jdx/mise-action@v2
        with:
          version: 2025.3.6
          install: true
          cache: true

      - name: Run swiftlint on missing files
        run: |
          which swiftlint
          swiftlint --version

          git diff HEAD^1 HEAD --name-only --diff-filter=AMCR \
            | grep -E "\.swift\$$"                            \
            || echo "No files added nor modified!"

          git diff HEAD^1 HEAD --name-only --diff-filter=AMCR \
            | grep -E "\.swift\$$"                            \
            | xargs --no-run-if-empty swiftlint lint --quiet --reporter github-actions-logging
