# Leka - iOS Monorepo
# Copyright APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Linters - pre-commit hooks

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swift_format:
    name: pre-commit hooks
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        files: [changed_files, all_files]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up mise
        uses: jdx/mise-action@v2
        with:
          version: 2025.1.7
          install: true
          cache: true

      - name: Install hooks
        run: |
          pre-commit install --install-hooks

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-
            pre-commit-

      - name: Run pre-commit hooks on all files
        if: matrix.files == 'all_files'
        run: |
          pre-commit run --show-diff-on-failure --color=always --all-files
          pre-commit gc

      - name: Run pre-commit hooks on changed files
        if: matrix.files == 'changed_files'
        run: |
          pre-commit run --show-diff-on-failure --color=always --files $(git diff --name-only -r HEAD^1 HEAD --diff-filter=AMCR)
